language: php

php:
  - 5.3
  - 5.4
services: mongodb

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev

notifications:
  irc:   "irc.freenode.org#vespolina"